language: go

go:
- 1.3
- 1.4
- tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

matrix:
  allow_failures:
    - go: tip

script:
- go get ./...
- go build ./...
- go test -v -cover -race -coverprofile=profile.out ./pkg/api
- goveralls -service=travis-ci -v -coverprofile=profile.out
